import { Navbar } from "./components/Navbar/Navbar";
import "./globals.css";
import styles from "./layout.module.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 60;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
